<?php

namespace Ben\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    public function findMediasByCategory()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m')
            ->from('BenGalleryBundle:Media', 'm')
            ->innerJoin('m.categories', 'c')
            ->where('c.id = 1')
            ->getQuery()
            ->getResult();
    }
}
