<?php

namespace Ben\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    public function findMediasByCategory($id)
    {
        return $this->createQueryBuilder('m')
            ->addSelect('c')
            ->join('m.categories','c','WITH' ,'c.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
