<?php

namespace Ben\TchatBundle\Entity;

/**
 * TchatPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TchatPostRepository extends \Doctrine\ORM\EntityRepository
{
}
